insert into team_members (name, role, bio, sort_order, published) select 'Omer Farooq', 'CEO, full-stack developer', 'Sets every build and stays in code. Product scope, architecture, and a path that starts with a rough idea and ends with something a customer can use.', 1, true where not exists (select 1 from team_members where name = 'Omer Farooq');

insert into team_members (name, role, bio, sort_order, published) select 'Muhammad Maaz Akram', 'AI automation engineer', 'Connects tools a business already has and removes manual steps between them.', 2, true where not exists (select 1 from team_members where name = 'Muhammad Maaz Akram');

insert into team_members (name, role, bio, sort_order, published) select 'Muhammad Abu Bakar Siddique', 'Design and marketing', 'Look of every product and story around it, so an offer is obvious before anyone reads a feature list.', 3, true where not exists (select 1 from team_members where name = 'Muhammad Abu Bakar Siddique');

insert into team_members (name, role, bio, sort_order, published) select 'Muhammad Ali', 'SEO, Meta ads, marketing', 'Search and paid social. Gets right pages in front of people already looking, and tunes ads that fill every gap.', 4, true where not exists (select 1 from team_members where name = 'Muhammad Ali');

insert into projects (name, url, summary, features, services, image_url, sort_order, published) select 'RestroManage', 'https://restromanage.com', 'Restaurant operations on phones and tablets a venue already owns. No POS terminal to buy.', 'Point of sale for dine-in, takeaway, and counter' || chr(10) || 'Online ordering and a branded storefront' || chr(10) || 'QR ordering at every table, straight to kitchen' || chr(10) || 'Floor plan, reservations, and reminders' || chr(10) || 'Kitchen display in place of paper tickets' || chr(10) || 'Inventory, staff attendance, and multi-location menus' || chr(10) || 'Live sales reporting' || chr(10) || 'Accounting sync for books a venue already uses', 'Product, full stack, SEO', '/work/restromanage.jpg', 1, true where not exists (select 1 from projects where url = 'https://restromanage.com');

insert into projects (name, url, summary, features, services, image_url, sort_order, published) select 'UniMondo', 'https://unimondo.uk', 'A study-in-Europe consultancy, starting with a first call and running through admissions and visa-ready departure.', 'Country and university shortlists' || chr(10) || 'Program pages with deadlines and tuition bands' || chr(10) || 'A staged application journey a student can follow' || chr(10) || 'Intake that carries GPA and IELTS inside one student file' || chr(10) || 'Counselor-led pages instead of a generic brochure', 'Web, design, marketing', '/work/unimondo.jpg', 2, true where not exists (select 1 from projects where url = 'https://unimondo.uk');

insert into projects (name, url, summary, features, services, image_url, sort_order, published) select 'USA Peptide Depot', 'https://usapeptidedepot.com', 'A research-catalogue storefront with lot paperwork, domestic shipping, and a checkout that stays in its lane.', 'Product catalogue with lot-specific documentation' || chr(10) || 'Research-use notices kept visible' || chr(10) || 'US fulfillment, tracking, and a free-shipping threshold' || chr(10) || 'A reconstitution calculator for laboratory volumes' || chr(10) || 'Account, order, and support paths', 'Web, full stack, SEO', '/work/usa-peptide-depot.jpg', 3, true where not exists (select 1 from projects where url = 'https://usapeptidedepot.com');

insert into projects (name, url, summary, features, services, image_url, sort_order, published) select 'Peptide Costa Rica', 'https://peptidecostarica.net', 'A regional storefront for this kind of catalogue, written and shipped for Costa Rica.', 'Local catalogue and product pages' || chr(10) || 'Checkout and shipping for that market' || chr(10) || 'Brand and page structure kept apart versus that US store', 'Web, design', '/work/peptide-costa-rica.jpg', 4, true where not exists (select 1 from projects where url = 'https://peptidecostarica.net');

insert into projects (name, url, summary, features, services, image_url, sort_order, published) select 'Vakeel Diary', 'https://vakeeldiary.com', 'Practice management for Pakistani advocates. Cases, hearings, and fees in one place instead of a paper diary.', 'Case and matter history' || chr(10) || 'Hearing dates, deadlines, and reminders' || chr(10) || 'Client records and documents' || chr(10) || 'PKR billing, payments, and invoices' || chr(10) || 'Roles for a solo chamber or a small firm', 'Product, full stack, design', '/work/vakeel-diary.jpg', 5, true where not exists (select 1 from projects where url = 'https://vakeeldiary.com');

insert into projects (name, url, summary, features, services, image_url, sort_order, published) select 'Battle Born Peptide', 'https://battlebornpeptide.com', 'A branded catalogue and checkout, with its own name, offer, and product pages.', 'Brand-specific storefront' || chr(10) || 'Product pages and checkout' || chr(10) || 'Structure ready for ads and search', 'Web, marketing', '/work/battle-born.jpg', 6, true where not exists (select 1 from projects where url = 'https://battlebornpeptide.com');

update projects set image_url = '/work/restromanage.jpg', sort_order = 1 where url = 'https://restromanage.com';
update projects set image_url = '/work/unimondo.jpg', sort_order = 2 where url = 'https://unimondo.uk';
update projects set image_url = '/work/usa-peptide-depot.jpg', sort_order = 3 where url = 'https://usapeptidedepot.com';
update projects set image_url = '/work/peptide-costa-rica.jpg', sort_order = 4 where url = 'https://peptidecostarica.net';
update projects set image_url = '/work/vakeel-diary.jpg', sort_order = 5 where url = 'https://vakeeldiary.com';
update projects set image_url = '/work/battle-born.jpg', sort_order = 6 where url = 'https://battlebornpeptide.com';

insert into offers (name, summary, points, sort_order, published) select 'Concept to launch', 'For a business that is still an idea. We leave you with an offer, a product or site, and a way to take first customers.', 'Scope and offer' || chr(10) || 'Name, pages, and brand' || chr(10) || 'Build through a usable launch' || chr(10) || 'A short plan for first leads', 1, true where not exists (select 1 from offers where name = 'Concept to launch');

insert into offers (name, summary, points, sort_order, published) select 'Product build', 'A working system: accounts, daily workflow, and screens a team will still open in six months.', 'Full-stack product' || chr(10) || 'Roles and permissions' || chr(10) || 'Billing or operations built in' || chr(10) || 'Handover a team can run', 2, true where not exists (select 1 from offers where name = 'Product build');

insert into offers (name, summary, points, sort_order, published) select 'Growth desk', 'After a product exists. Search, Meta ads, and a cleaned list of businesses to contact.', 'SEO on pages that can rank' || chr(10) || 'Meta campaigns and creative around them' || chr(10) || 'Lead lists on public business pages' || chr(10) || 'A monthly read on what to change', 3, true where not exists (select 1 from offers where name = 'Growth desk');

insert into offers (name, summary, points, sort_order, published) select 'Automation', 'Work that should not need a person every time: follow-ups, handoffs, reports, and tools talking to one another.', 'Map repeated steps' || chr(10) || 'Connect tools you already pay for' || chr(10) || 'A quiet system instead of one more spreadsheet', 4, true where not exists (select 1 from offers where name = 'Automation');
